### ISSUE TITLE
Support for Flutter 2.0

### ISSUE THREAD

**Issue by bssughosh** [am15h/tflite_flutter_helper#26]
We are trying to use the `tflite_flutter` package and for the image processor, we would need `tflite_flutter_helper`. 

But when we try to add this dependency in the flutter project, it depends on an older `tflite_flutter` version.

The latest `tflite_flutter` version is 0.6.0 and the helper package depends on 0.5.0.

Can the helper package be updated to depend on the latest tflite_flutter version?

If it would be updated then what would the ETA?

**Comment by am15h** [comment]
I will publish the update in the next few hours.

**Comment by FlorianGross** [comment]
It's now 2 days ago... How is the current status and the current ETA?

**Comment by am15h** [comment]
Sorry for the delay. Actually, the work got blocked due to https://github.com/dart-lang/sdk/issues/45771. I have switched to windows now. Null-safe versions of both `tflite_flutter` and `tflite_flutter_helper` will be published by tomorrow.

**Comment by am15h** [comment]
The null-safe libraries are now published., please use `tflite_flutter: ^0.8.0` and `tflite_flutter_helper:  ^0.2.0`.
