### ISSUE TITLE
tflite_flutter_helper not working with tflite_flutter_plugin 0.9.0

### ISSUE THREAD

**Issue by Kypsis** [am15h/tflite_flutter_helper#30]
Because tflite_flutter_helper >=0.2.0 depends on tflite_flutter ^0.8.0 and object_detection depends on tflite_flutter ^0.9.0, tflite_flutter_helper >=0.2.0 is forbidden.

**Comment by ofury** [comment]
@am15h could you update dependencies for tflite_flutter_helper?

**Comment by am15h** [comment]
Updated with v0.2.1 https://pub.dev/packages/tflite_flutter_helper.
